### ISSUE TITLE
How to capture the URL being generated each time?

### ISSUE THREAD

**Issue by rakeshranjan1986** [microsoft/interpret#20]
Dear Interpret Team,

How can I capture the URL being generated for the dashboard. I need to capture this URL and integrate with third party UI. If you can suggest an idea to overcome this technical hurdle, it would be of great help.

Rakesh

**Comment by interpret-ml** [comment]
Hi Rakesh - appreciate your response.

If you update to the latest (v0.1.7), there should be a `show_link(explanation)` method available. You can run it as shown below:

```
from interpret import show, show_link

# NOTE: 'show' must be called before 'show_link' for the given explanation(s).
explainers = [hist, lr_global, lr_perf, tree_global, tree_perf, ebm_global, ebm_perf]
show(explainers, share_tables=True)
url = show_link(explainers)
print(url)
```

Currently you have to pass a variable referencing a list to show and show_link, not an anonymous list for this to work. We will relax these requirements in the next release. This should be out later this week.

Will you require to change the base url as well for the integration?

**Comment by rakeshranjan1986** [comment]
Thanks a Lot!!!

**Comment by interpret-ml** [comment]
Closing issue. Feel free to re-open or create a new issue if you run into anything!
