### ISSUE TITLE
How to interpret the score on Y-axis of the global interpretation of each feature plot in classification model? 

### ISSUE THREAD

**Issue by bharathbolla** [microsoft/interpret#21]
Hi Interpret Team,
First of all congratulations for the fantastic job. This package is very useful to run and interpret models. 

Could you please give an explanation of the score on the Y axis of the global interpretation of the each feature plot?

Thanks
Bharath

**Comment by interpret-ml** [comment]
Hi Bharath,

Are you using the Explainable Boosting Machine? If so, for regression, Y-axis scores are the same unit as your target variable (ex: if you're predicting housing prices, the Y-axis scores directly represent price). For classification, the Y-axis represents log odds -- these get passed through a logit link function to get probability scores at prediction time. This is similar to how logistic regression operates, if that analogy is helpful.

-InterpretML Team

**Comment by tomasvanoyen** [comment]
Hi, 

Thanks for the excellent job. Following up on this question. 

Could you please give an explanation on how the overall importance of the each feature is computed when using the ExplainableBoostingClassifier? 

Thanks, 

Tomas

**Comment by interpret-ml** [comment]
Hi @tomasvanoyen, 

We had a discussion about overall feature importance here: https://github.com/microsoft/interpret/issues/12 

Happy to answer any questions if the discussion there is unclear!

-InterpretML Team
