### ISSUE TITLE
Could not find open port

### ISSUE THREAD

**Issue by anaveenan** [microsoft/interpret#23]
I am getting an error "RuntimeError: Could not find open port" when I use show comment. Is there a way to set up the ip address and port number to run the dashboard. Thanks 

import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
    header=None)
df.columns = [
    "Age", "WorkClass", "fnlwgt", "Education", "EducationNum",
    "MaritalStatus", "Occupation", "Relationship", "Race", "Gender",
    "CapitalGain", "CapitalLoss", "HoursPerWeek", "NativeCountry", "Income"
]
train_cols = df.columns[0:-1]
label = df.columns[-1]
X = df[train_cols]
y = df[label].apply(lambda x: 0 if x == " <=50K" else 1) #Turning response into 0 and 1

seed = 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=seed)

from interpret import show
from interpret.data import ClassHistogram

hist = ClassHistogram().explain_data(X_train, y_train, name = 'Train Data')
show(hist)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-59c992e2ff72> in <module>
      3 
      4 hist = ClassHistogram().explain_data(X_train, y_train, name = 'Train Data')
----> 5 show(hist)

~/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/visual/interactive.py in show(explanation, share_tables)
    120     except Exception as e:  # pragma: no cover
    121         log.error(e, exc_info=True)
--> 122         raise e
    123 
    124     return None

~/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/visual/interactive.py in show(explanation, share_tables)
    110         # Initialize server if needed
    111         if this.app_runner is None:  # pragma: no cover
--> 112             init_show_server(this.app_addr)
    113 
    114         # Register

~/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/visual/interactive.py in init_show_server(addr, base_url, use_relative_links)
     83     log.debug("Create app runner at {0}".format(addr))
     84     this.app_runner = AppRunner(
---> 85         addr, base_url=base_url, use_relative_links=use_relative_links
     86     )
     87     this.app_runner.start()

~/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/visual/dashboard.py in __init__(self, addr, base_url, use_relative_links)
     58                 msg = "Could not find open port"
     59                 log.error(msg)
---> 60                 raise RuntimeError(msg)
     61         else:
     62             self.ip = addr[0]

RuntimeError: Could not find open port

**Comment by interpret-ml** [comment]
Hi anaveenan, 

We try to automatically find an open port on your machine to host our visualizations at. Unfortunately, if we can't find an open port in a few tries, we'll raise this exception. 

Here's a workaround which lets you specify exactly what port to run the visualizations on:

```
from interpret import set_show_addr

set_show_addr(('127.0.0.1', 7001))

show(explanation)  # Will run on 127.0.0.1/localhost at port 7001
```

As long as you run the set_show_addr() method before calling show(), it should work. Just make sure that the port you set is open on your system!

**Comment by anaveenan** [comment]
Thank you for the quick response.
I get "GLIBC_2.14" error when I run the below command. Is there a way to solve this without root access -  in my conda env 

my os: 
Distributor ID:	CentOS
Description:	CentOS release 6.6 (Final)
Release:	6.6

from interpret.glassbox import ExplainableBoostingClassifier, LogisticRegression, ClassificationTree, DecisionListClassifier

ebm = ExplainableBoostingClassifier(random_state=seed)
ebm.fit(X_train, y_train) 


/lib64/libc.so.6: version `GLIBC_2.14' not found

**Comment by anaveenan** [comment]
Thanks for the response. suggested solution works for me
