### ISSUE TITLE
"GLIBC_2.14" error

### ISSUE THREAD

**Issue by anaveenan** [microsoft/interpret#24]
I get "GLIBC_2.14" error when I run the below command. Is there a way to solve this without root access - in my conda env

my os:
Distributor ID:	CentOS
Description:	CentOS release 6.6 (Final)
Release:	6.6

from interpret.glassbox import ExplainableBoostingClassifier, LogisticRegression, ClassificationTree, DecisionListClassifier

ebm = ExplainableBoostingClassifier(random_state=seed)
ebm.fit(X_train, y_train)

/lib64/libc.so.6: version `GLIBC_2.14' not found

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-14-e2f25093a7b6> in <module>
----> 1 from interpret.glassbox import ExplainableBoostingClassifier, LogisticRegression, ClassificationTree, DecisionListClassifier
      2 
      3 ebm = ExplainableBoostingClassifier(random_state=seed)
      4 ebm.fit(X_train, y_train)   #Works on dataframes and numpy arrays

~/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/glassbox/__init__.py in <module>
      5 from .linear import LogisticRegression, LinearRegression  # noqa: F401
      6 from .skoperules import DecisionListClassifier  # noqa: F401
----> 7 from .ebm.ebm import ExplainableBoostingClassifier  # noqa: F401
      8 from .ebm.ebm import ExplainableBoostingRegressor  # noqa: F401

~/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/glassbox/ebm/ebm.py in <module>
      5 from ...utils import perf_dict
      6 from .utils import EBMUtils
----> 7 from .internal import NativeEBM
      8 from ...utils import unify_data, autogen_schema
      9 from ...api.base import ExplainerMixin

~/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/glassbox/ebm/internal.py in <module>
     63 
     64 
---> 65 Lib = load_library(debug=False)
     66 
     67 # C-level interface

~/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/glassbox/ebm/internal.py in load_library(debug)
     59         is_debug = debug
     60 
---> 61     lib = ct.cdll.LoadLibrary(get_ebm_lib_path(debug=is_debug))
     62     return lib
     63 

~/anaconda/envs/fastai/lib/python3.7/ctypes/__init__.py in LoadLibrary(self, name)
    432 
    433     def LoadLibrary(self, name):
--> 434         return self._dlltype(name)
    435 
    436 cdll = LibraryLoader(CDLL)

~/anaconda/envs/fastai/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354 
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/narjunan/anaconda/envs/fastai/lib/python3.7/site-packages/interpret/glassbox/ebm/../../lib/ebmcore_linux_x64.so)

**Comment by interpret-ml** [comment]
Hi @anaveenan,

We just pushed some changes to the develop branch that should resolve this by using older versions of GLIBC (from 2006!).  We'll publish a new package shortly that includes this fix.  Thanks for reporting the issue!

-InterpretML Team

**Comment by interpret-ml** [comment]
Hi @anaveenan,

The latest 0.1.9 release should fix this error.  Can you please try it out and confirm.

Thanks,
-InterpretML Team

**Comment by anaveenan** [comment]
The error is fixed now. Thanks for helping
