### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by fhe-fr** [microsoft/interpret#29]
I'm trying to build a local version of demo.
Using VS 2017 and get an error during the build:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8020	The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	ebmcore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets	57	

I tried a "Retarget solution" with no success.

**Comment by fhe-fr** [comment]
I changed the platform toolset in the project property to VS 2017 and now I can build. but get an error at execution time: ebmcore_win_x64.dll is not a valid Win32 application

**Comment by interpret-ml** [comment]
Hi @fhe-fr,

For compiling on Windows, you'll need to use Visual Studio 2019 to build the core C++ library.  You can download a free copy of Visual Studio Community Edition from here:

https://visualstudio.microsoft.com/vs/

On Windows we only officially support building on VS2019, however I am pretty sure that the C++ will compile in VS2013-VS2017, or even MinGW/MinGW-64 with the correct project/solution file settings since the code itself only targets a minimum of C++11 and above.

Regarding the runtime error, can you verify if the DLL produced is 64-bit compatible?  Can you also post the output from ```dumpbin.exe /headers /imports ebmcore_win_x64.dll``` from a Visual Studio command prompt.

-InterpretML Team

**Comment by fhe-fr** [comment]
Let me run the dumpbin.exe as I could successfully compile on VS 2017.
One question, am I going to obtain at the end something that looks like: http://tmlready1.westus.cloudapp.azure.com:9523/
I'm preparing a demo for an AI event in France and my objective is to have the exact same demo locally.

**Comment by interpret-ml** [comment]
Hi @fhe-fr,

We're curious to know if/why you need to compile the C++ for your demo?  You should be able to replicate the dashboard locally with just the regular pip package:

```
pip install numpy scipy pyscaffold
pip install -U interpret
```

If you install the python package, we can send you an example Jupyter Notebook/Python script to replicate that demo locally on your machine.  If that sounds good to you, please email us at: interpret@microsoft.com

-InterpretML Team

**Comment by fhe-fr** [comment]
I creat a conda environment and did the pip install. I test with one of the example and it worked. So if you can send me the necessary noetbook it will be grate.
I don't want to run the notebook 1 by 1. there will be 150 participants and they make a lot of buzz on likedin around this event. So I need a nice looking html page as I used during Vivatech some weeks ago in Paris. You know the main point is that the URL that I shared with you has no SLA so I 'm affraid that the web site wont be up and running during my demo wich is on 26 June from 12 to 4 pm (French time).

**Comment by fhe-fr** [comment]
Hi I sent an email to the  interpret@microsoft.com to get to the notebooks to replicate locally the examples. But didn't get any response. Can you please suggest?

**Comment by interpret-ml** [comment]
Email should be sent out, let us know if you have not received it.

**Comment by fhe-fr** [comment]
Get the email

Thanks
