### ISSUE TITLE
How to get categorical variables in the graph?

### ISSUE THREAD

**Issue by anaquio** [microsoft/interpret#33]
I am opening an issue because I am trying to reproduce the results obtained in this graph:

![image](https://user-images.githubusercontent.com/50957724/60687150-0f9d2b00-9ead-11e9-9fa0-a11844e5deb4.png)

I would like to get the categorical features as text, just as it can be seen in the image. However, when doing it by myself, if I don't convert the categorical values to numeric I am getting an error, and therefore I am not able to reproduce the graph as it gets the number the variable was encoded with:

![image](https://user-images.githubusercontent.com/50957724/60687229-8fc39080-9ead-11e9-9892-94f43c73d020.png)

Do you know why is this happening and what should I do in order to get it with the text? Thanks

**Comment by interpret-ml** [comment]
Hi @anaquio, 

Are you using the ExplainableBoostingClassifier for this? If you pass in the text values directly to ebm.fit() and ebm.explain_local() as a Pandas dataframe, it should preserve the categories in the output. 

> if I don't convert the categorical values to numeric I am getting an error

What error are you running into? Could you paste the error message here and the code you are running?

Thanks!
-InterpretML Team
