### ISSUE TITLE
interpretation of local feature importances 

### ISSUE THREAD

**Issue by tomasvanoyen** [microsoft/interpret#34]
Hi, 
thank you for this nice package. 

It would be helpful if the examples where extended with some documentation on how the visualized results are computed. 

For instance, what puzzles me is the computation of the local feature importance values in relation to the predicted value considering the Explainable Boosting Classifier. 

How do they relate to each other? Is there a relation between them (as the model is a GAM I would expect as a first guess some linear relation, but it doesn't add up)? 

My apologies if the question reveals some ignorance on my side to standard literature. 

Kind regards, 

Tomas

########## 
EDIT below: 

by try and error, I believe I found the solution: the probability score given by the Explainable Boosting Classifier is computed as:

 `
def compute_p(rs):
    return 1./(1. + np.exp(-rs))

t = np.sum(ebm_local._internal_obj['specific'][0]['scores']) + ebm_local._internal_obj['specific'][0]['extra']['scores']
p = compute_p(t)
`

**Comment by interpret-ml** [comment]
Thanks for bringing up (and solving!) this issue @tomasvanoyen! We are in the process of writing up documentation to have formal answers to these questions :). 

You're right, the local feature importance values for classification are Log-Odds terms. Just like with logistic regression, these terms get added together, and the final value gets passed through the logistic link function (https://en.wikipedia.org/wiki/Logistic_function) to turn them into probability scores. 

-InterpretML Team
