### ISSUE TITLE
Bug in Notebook for reproducing table

### ISSUE THREAD

**Issue by theSparta** [microsoft/interpret#37]
In the UCI heart disease dataset used in the `load_heart_dataset` function in the [notebook](https://nbviewer.jupyter.org/github/Microsoft/interpret/blob/master/benchmarks/EBM%20Classification%20Comparison.ipynb), the label is given the second last column instead of the last column. The last column in the dataset corresponds to a location variable (and takes values such as 'Hungary', 'VA' etc).

**Comment by GISH123** [comment]
Yeah, thank you very much. Now we have to manually set the label to second last column to make it work.
Was very confused why the example is not working, now i know how to fix it on my own.

I kind of brute force to make the method to correctly get the right column, and removed missing values, if someone's interested though:

def load_heart_data():
    # https://www.kaggle.com/sonumj/heart-disease-dataset-from-uci
    df = pd.read_csv(r'heart.csv') 
    df = df.dropna()
    train_cols = df.columns 
    train_cols.drop('num') # here
    label = df.columns[-2] # here
    X_df = df[train_cols]
    y_df = df[label]
    dataset = {
        'problem': 'classification',
        'full': {
            'X': X_df,
            'y': y_df,
        },
    }
    
    return dataset

**Comment by interpret-ml** [comment]
Hi @theSparta and @GISH123 ,

Thank you so much for reporting this. It turns out we had the wrong link to the Kaggle dataset we used for the comparisons. This: https://www.kaggle.com/ronitf/heart-disease-uci is the correct link; we've gone ahead and updated the comment in the notebook. 

Really appreciate the help!

-InterpretML Team
