### ISSUE TITLE
Show function while on the remote cloud

### ISSUE THREAD

**Issue by GISH123** [microsoft/interpret#39]
Sorry if i have any grammatical errors.(not a native speaker)

I've read this issue: https://github.com/microsoft/interpret/issues/17

I think my problem is very similar, it might be some kind of server issues.

I have a virtual environment on amazon's aws ec2, opened jupyter notebook there, and connect the jupyter notebook on my local machine via ssh.

But when i use the show function(like the one in "Explaining Blackbox Classifiers.ipynb"), the plot will show "127.0.0.1 refused to connect".

Is there any way that i can still plot the interactive one on the cloud jupyter? 
I can sucessfully plot an interactive one in local jupyter, but on the cloud it just fails.
Thank you for your attention!

**Comment by interpret-ml** [comment]
Hi @GISH123 - thanks for the issue!

It sounds like you're pretty comfortable with port forwarding. :)

Behind the `show` method, there is a web server that requires an additional port forward separate to your Jupyter kernel.

You can configure the port for the backing web server like so:
```python
from interpret import set_show_addr
set_show_addr(('127.0.0.1', 7001))
```

At the same time, open local forwards for both Jupyter (8888) and the web server (7001):
`ssh user@host -L8888:localhost:8888 -L7001:localhost:7001`

Hope this helps, let us know how it goes, or if you have any more questions!

**Comment by mikewlange** [comment]
This finally works great without issue. 

This is Colab 5 min ago pip install. 

![!http://i.imgur.com/ygZdQkk.png](http://i.imgur.com/ygZdQkk.png)

For @interpret-ml - And you did it right too. 

You didn't shy away from react and used c++ for the expensive work. And not every constant has to be global. Nice. This is a testament to Visual Studio as well. c+ 14(?), js(react), and python same solution and ide. I found Interpret three days after it went live on GH, and it's in my top 10 open source projects of all time. Well done.

**Comment by interpret-ml** [comment]
Hey @mikewlange, 

We really appreciate the kind words, and we love your sense of humor from the other threads :). We take the architecture and design very seriously, and it's great to find someone who thinks like we do.

You're right, we've done a significant amount of work to enable visualization in cloud systems -- nice to hear it's working for you in Colab. Let us know if you have any further issues!

-InterpretML Team

**Comment by mikewlange** [comment]
Thanks! 

This is totally the wrong forum to write this. But what the hell, right. 

I've been trying to write an article about the top five technologies of 2019. And you're in the list. I just use way too many words, so I'll likely never finish. 

I'm putting together a notebook that will hopefully land me a job I just interviewed for. I hate interviewing. But I'm usually good at it. Such a pain. Haven't had to for like 10 years and I'm little desperate. Which is the worst in any sales situation. And interviewing is all sales. back then it was easy, say "I can make a website" and you're in. today companies are looking for things like, competence. What's going with tech? 

They didn't ask for work. But I rambled a little bit in the interview when discussing data models and a production workflow. I hate knowing what I'm talking about, but when I have to explain, I choke a little. 

I'm just going to have to make them have to say yes. it's foreclosure model using this data. https://www.fanniemae.com/portal/funding-the-market/data/loan-performance-data.html - anyway. I'll be using interpret, of course. 

Going to try and do a marathon coding session, so wish me luck. I'll make your product look good, actually it's be the other way around. 

Thanks for being a sounding board. :)

Cheers, 

Mike

**Comment by interpret-ml** [comment]
Good luck Mike!  We're rooting for you, and we love the idea of InterpretML helping out, to whatever small degree, in your interviews.  :)

-InterpretML Team

**Comment by saurk** [comment]
I am running into this issue on Azure AML compute cluster. I have setup the ssh port forwarding as well as 
_from interpret import set_show_addr
set_show_addr(('127.0.0.1', 7001))_

It says on the Jupyter Cell : The connection was reset.

This is the debug messages am getting on the ssh terminal:

$ debug1: Connection to port 7001 forwarding to 10.0.0.4 port 7001 requested.
debug1: channel 13: new [direct-tcpip]
channel 13: open failed: connect failed: Connection refused
debug1: channel 13: free: direct-tcpip: listening port 7001 for 10.0.0.4 port 7001, connect from 127.0.0.1 port 62265 to 127.0.0.1 port 7001, nchannels 14
debug1: Connection to port 8888 forwarding to 10.0.0.4 port 8888 requested.
debug1: channel 13: new [direct-tcpip]
