### ISSUE TITLE
Required  by libstdc++.so.6

### ISSUE THREAD

**Issue by huangwei2013** [microsoft/interpret#4]
Found Error：
   libstdc++.so.6: version CXXABI_1.3.8

I got libstdc++.so.6 but do not support CXXABI_1.3.8, as below
`CXXABI_1.3

CXXABI_1.3.1 
CXXABI_1.3.2 
CXXABI_1.3.3  
CXXABI_1.3.4 
CXXABI_1.3.5 
CXXABI_1.3.6 
CXXABI_1.3.7 
CXXABI_TM_1
`

when try the base example：

     from interpret.glassbox import ExplainableBoostingClassifier
     ebm = ExplainableBoostingClassifier()
     ebm.fit(X_train, y_train)

My Server:
    Centos7.5 ( Aliyun, Qcloud both tried)
    gcc/g++ 4.8.5  
    libstdc++.so.6.0.19 

Solution：
    Copy from somewhere a libstdc++.so.6.0.24 , an make a sofelink of libstdc++.so.6

Of course it‘s not problem of interpretML，but still a trouble for newbe .

**Comment by interpret-ml** [comment]
Hi huangwei2013,

Thanks for reporting this to us!  We were able to remove the dependency on libstdc++ by statically linking it in, which should simplify things for you and anyone else with older versions of that library.  The change has been pushed to the develop branch.  We'll be putting out a release in the next day or two that will merge it into master and to pypi.

**Comment by interpret-ml** [comment]
This now in master and on pypi.

**Comment by huangwei2013** [comment]
Great and thx a lot !
