### ISSUE TITLE
scoring on the continuous feature looks unreal

### ISSUE THREAD

**Issue by metariat** [microsoft/interpret#42]
This graphic show the scoring on a continuous variable, contrary to the spline regression, the score has a lot of volatility, it might overfit the local observations. I tried to tweak the fitting parametters to have something smoother, but no success. What's the recommendation?

![graphic](https://raw.githubusercontent.com/microsoft/interpret/master/examples/assets/readme_ebm_global_specific.PNG)

**Comment by metariat** [comment]
It looks like continuous features are cutted equally by length, not by exposure, so area with few exposure are giving more importance that it should be, it could be one of the reason why we have such volatility.

**Comment by mosew** [comment]
I'm also interested in this. Maybe one could add a regularization penalty to control the "first derivative" of the f_k's. Where in the code base is the optimization routine?

**Comment by interpret-ml** [comment]
HI @metariat,

Thanks for bringing this up -- it's a great point, and we've been having lots of active discussions on this.  @LaureFeuillet graciously made a pull request that provides alternative binning strategies, which might mitigate this issue.  It seems like there will not be a one size fits all solution to reducing volatility though, so it's a large area of work that we'll need to chip away at.

@mosew, the optimization routine is written in C++, and can be found here: https://github.com/microsoft/interpret/blob/master/core/DimensionSingle.h#L157
https://github.com/microsoft/interpret/blob/master/core/TreeNode.h#L149

The first file, "DimensionSingle.h" contains the subroutine  (GrowDecisionTree) to grow each individual decision stump that's used in the gradient boosting procedure. The second file, "TreeNode.h" contains the "Flatten" procedure which turns the decision trees into individual graphs. Definitely let us know if you have any questions, and rest assured, we'll keep investigating this on our side too :).

-InterpretML Team

**Comment by interpret-ml** [comment]
Closing for now, as quantile bins are available through Laure's PR here: https://github.com/microsoft/interpret/pull/45 .
