### ISSUE TITLE
error on show() method werkzeug.wrappers.json is not installed 

### ISSUE THREAD

**Issue by sid321axn** [microsoft/interpret#44]
hi, I am implementing the sample code but when I execute this code below:

```
from interpret import show

ebm_global = ebm.explain_global()
show(ebm_global)
```
I am receiveing following error
![error](https://user-images.githubusercontent.com/40556157/62521984-5c7a7580-b84e-11e9-8280-8ce48cd589b4.PNG)

**Comment by interpret-ml** [comment]
Hi @sid321axn - thanks for letting us know!

Have not seen this before, looks like a dependency issue within flask that itself or some of our dependencies have caused. 

Can you tell us what flask version you are running?
`pip show flask`

**Comment by interpret-ml** [comment]
Feel free to re-open this if it's still an issue!
