### ISSUE TITLE
support pairwise interactions

### ISSUE THREAD

**Issue by moyidang** [microsoft/interpret#49]
Does this library currently support finding pairwise interactions, or visualizing pairwise interactions?

**Comment by interpret-ml** [comment]
Hi @moyidang, 

Yes, ExplainableBoostingMachine supports finding and visualizing pairwise interaction terms. 

You can include interactions by using the "interactions" parameter when you initialize the ExplainableBoostingClassifier/Regressor:
```python
ebm = ExplainableBoostingClassifier(interactions=5, random_state=42)
```
and then you can call
```
ebm.fit(X_train, y_train) 
```
like usual.

If you pass "interactions" an integer n (ex: interactions=5), we will run FAST and automatically detect the "top-n" pairs, and include them in the training process. Alternatively, you can pass in a list of list of integers (ex: interactions=[[2,3],[4,5]]) which will force the algorithm to learn pairs on features 2/3 and features 4/5.

Using explain_global() and show() will render pairwise interactions as heatmaps in the Jupyter notebook experience. 

There's more discussion of this here: https://github.com/microsoft/interpret/issues/2
