### ISSUE TITLE
requirements.txt doesn't have all the requirements

### ISSUE THREAD

**Issue by dfrankow** [microsoft/interpret#5]
The README says:

```
pip install numpy scipy pyscaffold
pip install -U interpret
```

I am confused why the project requirements.txt (or equivalent) doesn't just also have numpy, scipy, pyscaffold, if they are .. well, required.

If they're already in the environment, they won't be installed, so that's harmless.

I see in setup.py they are listed separately, with the comment:

```
  # NOTE: Numpy here is a workaround to skope-rules' dependencies.
```

so I assume you have your reasons?

**Comment by interpret-ml** [comment]
Agreed, ideally we should have just 'pip install -U interpret'.
Clean package installation working across many different operating systems/venv is something we struggle with.

- Earlier, we tried having all the dependencies in 'install_requires' in setup.py. Unfortunately this wasn't enough as some of our dependencies require numpy/scipy at build/install time. See https://github.com/scikit-learn-contrib/skope-rules/issues/19 as an example. Specifically, `pip install -U interpret` can fail in a fresh venv.
- Pyscaffold was a similar last-minute addition to the README, it's required for SALib and will fail the interpret package installation in select environments (fresh venv for MAC OSX on one of the machines we tested with).
- We're likely going to add fresh package installs as part of our CI builds. Once that happens we can revisit this and hopefully find a cleaner solution.

**Comment by jamesmyatt** [comment]
I'm no expert, but my understanding is as follows:

* If you need packages installed when setup runs, then they belong in `setup_requires` (See https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords). But if they're required for your dependencies, then that should be handled by those dependencies; so I recommend submitting a PR upstream.
* Similarly, pyscaffold is only required by SALib when running its own setup.py, and interpret users should not need to worry about that directly.

**Comment by jamesmyatt** [comment]
Also it's worth being clear about what the purpose of the `requirements.txt` file is: https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by interpret-ml** [comment]
@jamesmyatt You're correct -- we're waiting on our upstream dependencies to merge PRs that fix these problems. For pyscaffold, we've run into edge-case issues where it is required on OS X. We'll be able to update the installation instructions as soon as upstream changes go through!

**Comment by interpret-ml** [comment]
With the latest releases (v0.1.13 onwards), the install should just be `pip install -U interpret`. We made one of the dependencies optional until upstream fixes are in.

The file `requirements.txt` is used (courtesy of @gliptak for the PR) for the standard install requirements of the package.

Hopefully, this will ease installation especially in the case where interpret is itself a dependency of another package (used to fail previously).
