### ISSUE TITLE
SHAP doesn't show feature names

### ISSUE THREAD

**Issue by github12364** [microsoft/interpret#51]
The SHAP local explanation chart doesn't display the names of the features.
![image](https://user-images.githubusercontent.com/31090863/63038376-e5f4fd80-be75-11e9-9466-0e389f915aea.png)

**Comment by interpret-ml** [comment]
Hi @github12364 - thanks for posting this.

Having a look at this now, did you pass data as a numpy array or a dataframe to SHAP?

**Comment by github12364** [comment]
Thank you!
