### ISSUE TITLE
pip install  Error (pyscaffold)

### ISSUE THREAD

**Issue by MissaouiAhmed** [microsoft/interpret#58]
Python 3.6 
hello when i run 

    pip install  -U interpret

i had the following error
Could not find suitable distribution for Requirement.parse('pyscaffold<3.1a0,>=3.0a0')

so i dowgraded the  pyscaffold package version as required

    pip install pyscaffold==3.0.0

then i tried to install again
i got 

    pyscaffold.exceptions.OldSetuptools: Your setuptools version is too old (<30.3.0). Use `pip install -U setuptools` to upgrade.

the probelme is that my  setuptools version is 41.2.0

thanks for help

**Comment by interpret-ml** [comment]
Hi @MissaouiAhmed,

Not sure why this is failing, one of our dependencies (SALib) uses pyscaffold. Will try to reproduce this in the next 1-2 days and get back to you.

What operating system are you running on?

**Comment by interpret-ml** [comment]
Feel free to reopen if this is still an issue!
