### ISSUE TITLE
How to interpret the result of `explain_perf` function?

### ISSUE THREAD

**Issue by vinhqdang** [microsoft/interpret#6]
Hi all

I am running the notebook:

https://github.com/microsoft/interpret/blob/master/examples/notebooks/Explaining%20Blackbox%20Regressors.ipynb

The result of `explain_perf` function:

![image](https://user-images.githubusercontent.com/4891112/57835650-344c1f00-77e9-11e9-83af-83fa5edce761.png)

How could I interpret the result, i.e. what are the x-axis and y-axis of the graph?

Many thanks

**Comment by interpret-ml** [comment]
Hi Vinh,

The graph is showing a histogram of residuals -- the real value minus the predicted value -- across the dataset. So the x-axis is the ranges of the residuals, and the y-axis is a count of how many instances fell into each bucket. The metrics in the title are more standard performance metrics (rmse is the root mean squared error, and R2 is the coefficient of determination). 

Not including x-axis and y-axis titles in this graph was an oversight on our part. Thanks for reporting this -- we'll fix it in the next update!

**Comment by interpret-ml** [comment]
Should be fixed in the latest release today (v0.1.1). Let us know if you have further issues, thanks!
