### ISSUE TITLE
Feature importance with interactions

### ISSUE THREAD

**Issue by yingboli** [microsoft/interpret#65]
Thank you for giving a detailed explanation on feature importance on this page (https://github.com/microsoft/interpret/issues/12). My question is what if the EBM model has interactions (say, I use the argument `interactions = 10` when training the EBM model `ExplainableBoostingRegressor`, so it has 10 pairwise interactions).

In particular, for a given feature, if some interactions containing it are selected, would those be involved in the calculation of "how each train data point is scored by that feature"? Would this affect the global interpretation of the model, and/or the local interpretation? 

Thank you.

**Comment by interpret-ml** [comment]
HI @yingboli, 

Great question! Right now, we rank the interaction terms independently of the "main effect" terms in the overall feature importance calculations. Each interaction will show up as its own term, and will not benefit/hurt the importance of its underlying "main effect" (single feature) terms. 

For example, here's what the overall feature importance looks like for the "Adult" dataset trained with some interactions:

![image](https://user-images.githubusercontent.com/50031429/65835906-27245e00-e2ba-11e9-81b2-32c46a48e2e7.png)

As you can see, EducationNum and MaritalStatus both show up, and the interaction "EducationNum x MaritalStatus" also ranks (lowly) on the overall importance list. The existence of the interaction term did not penalize or benefit the main effect terms in any way in terms of overall feature importance.

In terms of the global interpretation of the models: Yes, interactions do affect this. You can think of interactions as "corrections" on a set of main effects, and they are important to consider while reasoning about the model's overall behavior. In our experience, it is rare for interactions to be incredibly globally impactful -- it's more likely that they provide important, meaningful corrections to small portions of the population. 

For local interpretations, you can rank the contribution of the interaction term alongside every main effect -- they are simply additional additive components like every single feature term. Interaction terms can be very impactful to individual local explanations. For example, you can see how "CapitalGain" affects this single prediction positively, and how several interactions terms with "CapitalGain" affect the prediction both positively and negatively. 

![image](https://user-images.githubusercontent.com/50031429/65835895-107e0700-e2ba-11e9-84ef-b289fce0b35a.png)

Please let us know if you have any further questions!

-InterpretML Team

**Comment by yingboli** [comment]
Great! Thank you for the information.
