### ISSUE TITLE
Example notebooks are broken

### ISSUE THREAD

**Issue by jklaise** [microsoft/interpret#78]
It appears that they haven't been updated, e.g. `from interpret import show` results in:
```
ImportError                               Traceback (most recent call last)
<ipython-input-5-49d410d1936e> in <module>
----> 1 from interpret import show
      2 from interpret.perf import ROC
      3 
      4 blackbox_perf = ROC(blackbox_model.predict_proba).explain_perf(X_test, y_test, name='Blackbox')
      5 show(blackbox_perf)

ImportError: cannot import name 'show' from 'interpret' (unknown location)
```

Is there any documentation about the current usage of the library?

**Comment by interpret-ml** [comment]
Hi @jklaise,

The example notebooks should still be accurate -- this sounds like an installation related bug. Would you mind reinstalling the library, or testing it in a new Python environment, and seeing if you get the same error?

Thanks for reporting this!

**Comment by jklaise** [comment]
Hmm it works when installing in a fresh environment but not when upgrading the older version in my existing environment (even with pip cache disabled), any pointers why this would be? Thanks!
