### ISSUE TITLE
Install Fails - Greenlet

### ISSUE THREAD

**Issue by BrianMiner** [microsoft/interpret#8]
I am trying to pip install interpret and currently the following error appears to be stopping the install. Any ideas for getting around this and proceeding?

I am using Ubuntu 16.04
`Cannot uninstall 'greenlet'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by Ceasers** [comment]
Hi BrianMiner, 

Have you fixed the problem? Can you share how?

**Comment by interpret-ml** [comment]
Hi @Ceasers - just ran into the same issue incidentally. Try running this:
`pip install interpret --ignore-installed greenlet`

Apparently pip cannot remove distutils-installed packages (often these packages are installed by the OS). 
So the command above will ignore trying to install over it.
