### ISSUE TITLE
how can I specify exactly which ip/port to run the visualizations ?

### ISSUE THREAD

**Issue by Fyweven** [microsoft/interpret#81]

**Comment by Fyweven** [comment]
RuntimeError: Could not find open port.
                Consider calling `interpret.set_show_addr(("127.0.0.1", 7001))` first.

set_show_addr(("127.0.0.1", 8081))
hist = ClassHistogram().explain_data(X_train, y_train, name = 'Train Data')
show(hist)

**Comment by interpret-ml** [comment]
Hi @Fyweven, 

```interpret.set_show_addr``` is the right method to call to set a custom port and address combination. You can import it directly from interpret, exactly as you pasted above:

```python
from interpret import show, set_show_addr

set_show_addr(("127.0.0.1", 7080))   # takes in a tuple of (ip_addr : str, and port : int)

show(explanation) # Will run on 127.0.0.1/localhost at port 7080
```

If this doesn't work (for example, if you can't open up any additional ports on your machine), consider switching to our inline visualization provider by running this at the start of your notebook/script:

```python
from interpret.provider import InlineProvider
from interpret import set_visualize_provider

set_visualize_provider(InlineProvider())
```

The inline provider is an experimental new addition that doesn't require a new port to be opened for the interactive visualizations to render. Please let us know if you have issues with this, as it's still in active development!

-InterpretML Team

**Comment by Fyweven** [comment]
switching to inline visualization provide works for me
Thanks very much

**Comment by Ajdin2022** [comment]
Switching to InlineProvider doesn't fix the rendering issue for me. Any ideas why? Thanks a lot.
