### ISSUE TITLE
show() does not seem to return anything

### ISSUE THREAD

**Issue by Shalenden** [microsoft/interpret#82]
Dear,

I've tried to run the python notebook example, model seems to fit but when trying to use:

ebm_global = ebm.explain_global(name='EBM')
show(ebm_global)

ebm_perf = ROC(ebm.predict_proba).explain_perf(X_test, y_test, name='EBM')
show(ebm_perf)

it doesnt do anything, i dont seem to see any ebm_global or ebm_perf being created either.

I'm trying to run it on spyder in a python 3.7 environment.

**Comment by peractio** [comment]
You'll need to use Jupyter for `show`, because it has a server behind the scenes driving the visualizations you see. Alternatively, you could use `preserve` to get a separate `html` file: https://github.com/microsoft/interpret/issues/52#issuecomment-523660912

```
from interpret import preserve
# preserve(ebm_global, 'Age', file_name='global-age-graph.html')
preserve(ebm_global, 'Age')

# preserve(ebm_local, 0, file_name='local-age-graph-0.html')
preserve(ebm_local, 0)
```

**Comment by Shalenden** [comment]
That worked, thanks
