### ISSUE TITLE
joblib is required in interpret core

### ISSUE THREAD

**Issue by wamartin-aml** [microsoft/interpret#89]
joblib is a required module for interpret core because of its use in provider/compute.py. It should be in the `required` extra rather than the `ebm` extra.

**Comment by wamartin-aml** [comment]
Or the dependency on scikit-learn should be increased to >=0.21 so that joblib will be required, but this doesn't accurately reflect the actual imports in the package.

**Comment by interpret-ml** [comment]
Hi @wamartin-aml,

Good catch. Requiring joblib sounds ideal for required extra. Thanks for developing the PR!
