### ISSUE TITLE
Dependency on Matplotlib 2.1.0 in Linux

### ISSUE THREAD

**Issue by puneethmishra** [microsoft/interpret#9]
Hi ,

I'm trying to install on a linux docker. It seems there is a dependency on the older version of matplotlib and it does not install fine. The latest version of matplotlib 3.0.3 is installing fine. Can we please upgade the dependency or else please suggest me a workaround. 

ERROR: Complete output from command python setup.py egg_info:
    ERROR: IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [2.1.0]
                    python: yes [3.7.3 | packaged by conda-forge | (default, Mar
                            27 2019, 23:01:00)  [GCC 7.3.0]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.16.3]
                       six: yes [using six version 1.12.0]
                  dateutil: yes [using dateutil version 2.8.0]
    backports.functools_lru_cache: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [using pytz version 2019.1]
                    cycler: yes [using cycler version 0.10.0]
                   tornado: yes [using tornado version 6.0.2]
                 pyparsing: yes [using pyparsing version 2.4.0]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: yes [version 3.14159265]
                   pdftops: no
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png * Try installing freetype with `apt-
                            * get install libfreetype6-dev` * Try installing png
                            * with `apt-get install libpng12-dev`
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-tvjuo8p6/matplotlib/

**Comment by interpret-ml** [comment]
Thanks for reporting this! 

One of the packages we depend on is currently pinning a lower version of Matplotlib. As a workaround, if you try reinstalling again (pip install -U interpret), it might work. We're working with the package owner to update the dependency.

**Comment by puneethmishra** [comment]
I think it's the LIME package. Tried it out , but still same issue.

**Comment by interpret-ml** [comment]
Looks like they're trying to fix it in this issue: https://github.com/marcotcr/lime/issues/297

Their repo has the fixed code, it just needs to be pushed to PyPi.

**Comment by interpret-ml** [comment]
Hi @puneethmishra, 

LIME just released an update on PyPi (v0.1.1.34), which should fix the dependency problem. Can you see if this resolved your installation issue?

**Comment by puneethmishra** [comment]
Thanks a ton its working fine now.
